### PR TITLE
WIP: Issue/492 empty tables

### LINKED ISSUE #492: Add new check for empty tables
Create an error for the case when the table tag has no tr's nested inside of it.

### PR DESCRIPTION
**Pull request by AlanFCMV**
Closes #492 

Waiting on a new phpally version update.
Needs a ufixit form that allows you to delete the table.

### CODE REVIEW

**Comment by bagofarms** [comment]
I'm thinking we can go ahead and merge this so the feature gets out there, then we can create a new issue for the UFIXIT.

**Comment by rob-3** [comment]
> I'm thinking we can go ahead and merge this so the feature gets out there, then we can create a new issue for the UFIXIT.

I am happy to merge this; as it doesn't appear to break anything, but I also can't get the event to fire. The logs don't show it as even recognized by UDOIT, and my efforts to write a form for it don't appear to do anything. I recommend keeping this open until someone figures out how to write a form for it.

**Comment by bagofarms** [comment]
Updated code with latest 3.3.0, but I am also unable to get the error to trigger.  I'm going to push this off for a future release.

**Comment by bagofarms** [comment]
I was able to get it to trigger!
Screen Shot 2022-12-16 at 4 57 58 PM

**Review by dmols — APPROVED** [review]
Empty table warning activates on my end as well! All other checks work as intended. Clear to push!

**Comment by dmols** [comment]
I'm unable to replicate the solution this time around. Could you take a look when you get a chance, @taheralfayad? Let me know if you see something similar to what Jacob posted above.

**Comment by dmols** [comment]
Was able to trigger this again. Will test to see if it's good for merge. I'll open an issue to implement a UFIXIT form to go along with the rule.

**Review by taheralfayad — APPROVED** [review]
LGTM

**Review by dmols — COMMENTED** [review]
Changes looked good; merged to dev for now! Will be adding an issue to tackle the implementation of a UFIXIT form in the future. Great work!

**Pull request merged**
