### PR TITLE
Issue/431 unlisted videos should be suggestions

### PR DESCRIPTION
**Pull request by jrsilveti**
Merged Issue 200/ test for unavailable videos into dev/2-6-0.

Changed the errors for unlisted videos into suggestions.

### CODE REVIEW

**Comment by jrsilveti** [comment]
Fixed unlisted videos showing up as an error and a suggestion.

**Comment by bagofarms** [comment]
This got missed for 2.6.0 because it was missing the milestone.  Moved to 2.7.0

**Comment by bagofarms** [comment]
Unfortunately, I'm going to have to close this issue without merging.  I tested the code, and it works perfectly, but the same feature was implemented in a different way as part of checking for caption language in #434 .  This only does a single API call rather than two, which is the primary reason for not merging this feature.

**Comment by bagofarms** [comment]
Actually, I thought this over some more.  We have API caching within the same scan, so adding this shouldn't result in any extra API usage.  I will need to go in and remove the "manual check required" code from Ethan's code, though.

**Comment by bagofarms** [comment]
Recreated in #547 so that I can make changes to the code.

**Pull request closed without merging**
