### PR TITLE
New redirected and broken link tests and UFIXITs

### PR DESCRIPTION
**Pull request by emilysachs**
- Fixes issue #205 
- Added ability to turn redirect check on/off in config
- Altered UDOIT.php to run cURL requests on all links simultaneously/asynchronously at the end of each content section so as to avoid timeouts
- Added UFIXIT for redirected link that also updates the node text with the new url if it matches the old url
- Minor improvements to aSuspiciousLinkText check
- Added time elapsed info to UDOIT fail error message with a suggestion to scan content sections individually

### CODE REVIEW

**Comment by emilysachs** [comment]
Addendum:
-Added broken link test and UFIXIT for issue #204
-Changed config to cover all link tests
-Added special conditions for links to course content
-Improved UFIXIT for redirects regarding node text
-Added jquery to set links in preview box to open in new tab

**Comment by bagofarms** [comment]
This one modifies a lot of files, and will likely require some rework.

**Comment by jasonmatos23-git** [comment]
- Merged old code with dev/v2-8-0
- Fixed Travis errors
Next up:
- Regex needs to be added to not accidentally mark a link as redirected when it is not (e.g. 'google.com' shows up as redirected when 'www.google.com/' does not)
- Modify linkTest function to account for 'base_uri' element no longer being in the Udoit class

**Comment by jasonmatos23-git** [comment]
Fully updated this branch.
- Regex added to ignore 'http', 'www', and trailing '/' when testing for redirects
- Ufixit auto populated with the redirected links
- Within canvas links now show up as broken/redirected. Had to add two additional (optional) parameters to scanContent in Udoit class to support this.

**Review by jasonmatos23-git — APPROVED** [review]

**Comment by jasonmatos23-git** [comment]
Last commit resolves conflict with dev branch.

**Review by AlanFCMV — APPROVED** [review]

**Pull request merged**
