### PR TITLE
Phpunit9 upgrade and Github Actions

### PR DESCRIPTION
**Pull request by ottenhoff**
1) Upgrade to phpunit9
2) Drop Travis (https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)
3) Use Github Actions
4) Build across matrix of PHP versions and OS
5) Update a couple of dependencies

### CODE REVIEW

**Comment by ottenhoff** [comment]
You can see the Github actions runs here:

  https://github.com/ottenhoff/UDOIT/actions

**Comment by ottenhoff** [comment]
Any thoughts on this PR? I definitely recommend Github Actions over Travis. It provides better flexibility and Travis is no longer as friendly to OS projects

**Comment by bagofarms** [comment]
I'm sorry I haven't reviewed this yet.  My other duties took over.  I'm hoping @iturgeon can take a look at it soon.

**Comment by ottenhoff** [comment]
Are you interested in these changes? Do you want me to resolve the conflicts?

**Comment by bagofarms** [comment]
Yes!  We are working on merging this in.  I'll resolve the conflicts and commit it in the next week or so.

**Pull request merged**
