### PR TITLE
Github Actions with Database Creation

### PR DESCRIPTION
**Pull request by ottenhoff**
This is currently failing, but the idea is to test all supported DBs during the PR CI run.

### CODE REVIEW

**Comment by ottenhoff** [comment]
I'm assuming that these doctrine migrate runs should work on both Postgres and MySQL on a fresh install?

**Comment by bagofarms** [comment]
@jasonmatos23-git Should those migrations work on MySQL?

**Comment by jasonmatos23-git** [comment]
The only migrations that work on MySQL are Version20210910203121 which is to rename the 'user' table to 'users', and Version20210525163808 which is the original migration provided by cidilabs. Neither of them works with Postgres.
Version20210910210740 is the only one that works for Postgres, and does not work with MySQL.

There also does not seem to be a way to combine the two database setup migrations because of differences in function names and data types, for example 'timestamp without time zone' is 'datetime' in MySQL

**Comment by ottenhoff** [comment]
Thanks but now I'm even more confused as to DB support in main branch. How does a new user stand up a database?

**Comment by bagofarms** [comment]
@ottenhoff It looks like you got it right.  I'm going to test this right now and hopefully get it merged today.

**Review by bagofarms — APPROVED** [review]

**Pull request merged**
