### PR TITLE
Ensure we only try to process reponse as JSON for files

### LINKED ISSUE #209: process.php returns content length of zero, causing error
this JavaScript error occurs after using UFIXIT:

```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.success (default.js?cachebuster=1483561097:409)
    at j (jquery-2.1.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.1.1.min.js:2)
    at x (jquery-2.1.1.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.1.1.min.js:4)
```

This has been traced back to process.php returning content with a length of zero.  Here are the headers process.php returns:

```
HTTP/1.1 200 OK
Connection: keep-alive
Date: Wed, 04 Jan 2017 20:18:45 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Via: 1.1 vegur
```

### PR DESCRIPTION
**Pull request by cooperfellows**
None of the other Ufixits return JSON (for now....)

This resolve #209

### CODE REVIEW

**Comment by cooperfellows** [comment]
Any idea when you may get a chance to merge this in? I'm holding off on updating our production instances until this is resolved. Hoping to roll out the latest release for our new semester starting in a week or so. Hoping to provide an estimated timeline back to our eLearning team.

**Comment by bagofarms** [comment]
I am having trouble getting UFIXITs for non-files to work.  I keep getting a 403 Forbidden error for process.php.  I was investigating the issue, but it would be helpful to get you to double-check the same thing on your installation.  If you don't receive a 403 error, then it's probably an issue with our server.

**Comment by cooperfellows** [comment]
Hm. Sure thing. I will take a look on a fresh deployment today or tomorrow
morning. I did run through a bunch of fixes after deploying this fix last
week and it worked right. Thanks for the feedback, will touch base again
soon.

**Comment by bagofarms** [comment]
Ok, i just did another test, and i can't replicate the issue on my system again.  I'm going to call this one good.  I noticed some other issues that also exist in Master.  Yay, more issues!

**Pull request merged**
