### PR TITLE
Mesa CTL security updates, finalized templates, tons of code cleanup / standardization

### PR DESCRIPTION
**Pull request by iturgeon**
First, thanks to @jwbowles for the #152 which started this major endeavor.

Adds a `Util` class with common functions.
Adds $UDOIT_ENV variable to hold the current environment for testing or production.
Finally converted the rest of the mixed logic/display code to use templates.
Added output filtering of variables that may be dangerous in templates
Added Input filtering to help protect from XSS attacks
Fixed lots of issues that look like they popped up as changes in html structure occurred over time.
Switched to standard of storing jquery objects in variables with starting with `$`
Switched to single quoted strings by default in javascript
Cleaned up and updated some css styles for the reports page

### CODE REVIEW

**Comment by jwbowles** [comment]
Awesome! We will do a scan on this repository to verify any other security issues.

**Comment by techrangerfj** [comment]
Issues Found: 

* Throbber appear on Save PDF Button does not disappear after PDF is processed and downloaded
* Within exported pdf  'process' is mispelled
⋅⋅[image of error](http://i67.tinypic.com/2ldzuit.jpg "image of error 1")
* Also note space between error frequency and 'x' above in image
*See below. After submitting, error preview does not disappear and instead it remains, add's a 2nd count which appears to be off by 1, and UFIXIT doesn't actually work.
⋅⋅[image of error](http://i67.tinypic.com/opqk92.jpg "image of error 2")

**Comment by bagofarms** [comment]
@jwbowles did you find any issues with this merge?

**Comment by bagofarms** [comment]
@iturgeon Module URLs and Unscannable files do not appear in the report.  I believe i have tracked this down to inconsistencies in the templates/partials/results_unscannable.php and results_module_urls.php.

Adding this line to the top of results_unscannable.php and results_module_urls.php should fix it:
`$items = $content_group->items;`

**Comment by bagofarms** [comment]
Additionally, the UFIXIT for imgHasAlt is not appearing.

**Comment by iturgeon** [comment]
Ok, I've fixed up the $items problem, working on imgHasAlt

**Comment by iturgeon** [comment]
imgHasAlt appears to be working in my tests

**Comment by iturgeon** [comment]
@bagofarms looks ready to me - sooo many changes

**Comment by bagofarms** [comment]
Issues found:

- UFIXIT for table headers doesn't work
- UFIXIT for "Link text should be descriptive" and "Links should contain text" deletes the link instead of inserting the text.
- UFIXIT for "Image elements should have an ALT attribute" does not appear (I will test to see if this issue exists in another branch.)

**Comment by bagofarms** [comment]
Ok, looks like we've had the "imgHasAlt" UFIXIT issue before on this pull request, so it's definitely legitimate.

**Comment by iturgeon** [comment]
should fix the first 2, still working on imgHasAlt

**Comment by bagofarms** [comment]
I've confirmed that those two issues were fixed.  Waiting until you've completed the third fix before i do a more thorough review.

**Comment by iturgeon** [comment]
UFIX IT for image alt tags back and working.

**Comment by iturgeon** [comment]
Unscannables fixes, there was a bug in my string concatenation when building the files api url.  Did a little more code clean up.

**Comment by iturgeon** [comment]
Happy to see this finally make it back into mainline.  Thanks to everyone involved!  I'll try not to rewrite the entire codebase for future pull requests :)

🏆 👑 🎉 👍  @techrangerfj @bagofarms @jwbowles

**Pull request merged**
