### PR TITLE
Fix color contrast issue

### PR DESCRIPTION
**Pull request by cooperfellows**
The background color was being passed to the server and interpreted as
the forground color by mistake. The index of the "newcontent" field name
needed to be switched.

This solves #203

### CODE REVIEW

**Comment by cooperfellows** [comment]
@emilysachs Are you sure we want to change the library code? The only reason that is "backwards" in reporter.static.php is because of the way we are sending the data.

It would be my preference, but I will obviously defer to your team, to change our code to work with the Library as it exists. Does that make sense?

**Comment by emilysachs** [comment]
Let me take another look! I only tried altering the library because when I pulled in your branch I was still seeing an issue. Perhaps there's something else affecting it.

**Comment by cooperfellows** [comment]
If you continue to see issues with the branch (without changing the reporter code) I will take another look. 

I've been deploying each PR branch to Heroku and doing manual testing each time, so I could have missed something.

**Comment by emilysachs** [comment]
@cooperfellows It looks like the problem actually has to do with the order of the colors in the attributes. When I test it on a span with "background-color: #333333; color: #003366;" it works, but "color: #003366; background-color: #333333;" shows up as flipped in UDOIT. So we'll need to add in a way to put the attributes in the right order that matches the way our code is referencing them. That being said, while testing I also noticed that the contrast test doesn't recognize a case like 
`<span style="background-color: #333333;"><span style="color: #003366;">test</span></span>`
correctly and treats each span tag as a separate problem if it triggers a contrast error by itself. Not sure yet if it's worth opening a new issue for this, or if it might be an easy fix.

**Comment by cooperfellows** [comment]
Good eyes @emilysachs, The second issue that you raised, nested contrast issues, are going to be harder to solve I imagine, that may warrant a new issue.

The first one (attribute ordering causing a problem) makes total sense, and I think should be resolved as a part of this issue. I'm not sure how much time I can give that this week (or next honestly), but I will keep progress posted to this PR.

**Comment by emilysachs** [comment]
@cooperfellows That's what I was guessing, I'll go ahead and open a new issue for it. I'm just about to leave for today but I'll take a shot at the attribute ordering tomorrow if that's alright.

**Comment by cooperfellows** [comment]
Go ahead and do whatever you need to @emilysachs, I won't be able to look at this until mid next week at the earliest.

**Comment by emilysachs** [comment]
Attribute ordering resolved here https://github.com/ucfopen/UDOIT/pull/237

**Comment by bagofarms** [comment]
Do we need this PR anymore, or does PR #237 fix it?

Also, just a quick note:  We have already heavily modified the Quail code, and the PHP version is not maintained anymore, so I'm comfortable with modifying it directly for things like this in the future.

**Comment by emilysachs** [comment]
@bagofarms I pulled the changes from this PR into 237 before adding the extra fixes on top of it, so I believe we can close this one.

**Pull request closed without merging**
