### PR TITLE
Add configuration variable for app name in Canvas

### PR DESCRIPTION
**Pull request by cooperfellows**
This is a re-roll of PR #150, which resolved issues #149. Let me know if anything looks out of place.

### CODE REVIEW

**Comment by bagofarms** [comment]
I can't get this to work on a non-Heroku install.  I even replaced the reference to the environment variable in localConfig.php to a hard-coded string with no luck.  It looks like udoit.xml.php isn't loading the settings.php or localConfig.php files, so $canvas_nav_item_name is always undefined.

**Comment by cooperfellows** [comment]
I see what's missing from that file, it's something like this:

```php
// Get tool configuration values from the correct config file
if (getenv('USE_HEROKU_CONFIG'))
{
	try {
		require_once('../config/herokuConfig.php');	
	} catch(Exception $e) {
		//$logger = new \Monolog\Logger('udoit');
	}
	
	if(!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
		$_SERVER['HTTPS'] = 'on';
	}
}
else
{
	try {
		require_once('../config/localConfig.php');	
	} catch (Exception $e){
		// Log using Monolog
	}	
}
```

I'd like to log a failure if we either of these requires fails, but im not sure how to use Monolog, any examples?

**Comment by bagofarms** [comment]
config/settings.php already handles determining whether you are in Heroku or a traditional install, so all you need to do is load it.  See https://github.com/ucfopen/UDOIT/blob/master/config/settings.php#L9

**Comment by cooperfellows** [comment]
Thanks @bagofarms, I obviously haven't looked at the big re-write close enough, apologies for that.

**Pull request merged**
