### PR TITLE
Enhancement  #12 Implemented

### PR DESCRIPTION
**Pull request by techrangerfj**
See issue for details

### CODE REVIEW

**Comment by bagofarms** [comment]
I was unable to test this due to the files scan timing out.  This course has not had a problem with the files area timing out before.

Also, please remove jscolor and the reference to it in udoit.php, since it is installed through Bower now.

**Comment by techrangerfj** [comment]
I'm attempting to implement feature that shows modules in which file is added to @bagofarms

**Comment by bagofarms** [comment]
Functionally, it checks out, but please add more space between the file name and the "Directory:"
https://www.dropbox.com/s/3vkxgdknc6uuoiw/Screenshot%202016-03-31%2017.44.25.png?dl=0

**Comment by bagofarms** [comment]
The PDF view of the files runs together.  See screenshot:  https://www.dropbox.com/s/44q5t0mo2lv41j5/Screenshot%202016-05-04%2014.59.24.png?dl=0

**Comment by techrangerfj** [comment]
@bagofarms adjusted

**Comment by iturgeon** [comment]
I merged this code into the current pull request.  Tests pass, and output looks good to me. 

screen shot 2016-12-14 at 10 07 12 pm

**Comment by emilysachs** [comment]
Simplified and added module locations here https://github.com/ucfopen/UDOIT/pull/278

**Pull request closed without merging**
